services:
  web:
    build: 
      context: ./celery_email_project
      dockerfile: dockerfile
    container_name: django
    command: gunicorn celery_email_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - celery_email_project/.env
    depends_on:
      - redis

  celery:
    build:
      context: ./celery_email_project
      dockerfile: dockerfile
    container_name: celery
    command: celery -A celery_email_project worker -l info
    volumes:
      - .:/app
    env_file:
      - celery_email_project/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./vue-email-sender
    container_name: frontend
    ports:
      - "8080:80"
